### ISSUE TITLE
Error al querer instalar pylint con Pip desde VSC en Win7

### ISSUE THREAD

**Issue by cjadeveloper** [hcosta/instalardjango.com#1]
Hector, me arroja este error si quiero elegir instalar _pylint_ con _pip_ desde el VSC. Aclaro que al VSC ya lo tenía instalado (con git incluido):

`
Microsoft Windows [Versión 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Reservados todos los derechos.

D:\code\python>activate py36

(py36) D:\code\python>C:/Miniconda3/envs/py36/python.exe -m pip install -U pylint
Traceback (most recent call last):
  File "C:\Miniconda3\envs\py36\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Miniconda3\envs\py36\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Miniconda3\envs\py36\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Cristian\AppData\Roaming\Python\Python36\site-packages\pip\__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Users\Cristian\AppData\Roaming\Python\Python36\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "C:\Users\Cristian\AppData\Roaming\Python\Python36\site-packages\pip\download.py", line 5, in <module>
    import getpass
  File "D:\code\python\getpass.py", line 9, in <module>
    usuario = getpass.getuser()
AttributeError: module 'getpass' has no attribute 'getuser'
`

**Comment by cjadeveloper** [comment]
Ejecuté `pip install -U pylint` y lo instaló bien, aunque unas advertencias por cada paquete instalado (en amarillo):

`Cache entry deserialization failed, entry ignored`

Hay algún problema en hacerlo así?

**Comment by hcguz** [comment]
Hola Cristian, la opción -U actualiza el paquete a la versión más reciente

![image](https://user-images.githubusercontent.com/748822/39336074-f1c0353e-49b5-11e8-9ce1-968ab24a7147.png)

Es curioso que te diera ese fallo.

Si no te hubiera funcionado te habría recomendado instalar con conda, desde el propio entorno virtual:

```
conda install pylint
```

Quizá actualizar el gestor pip a la última versión solucionaría los warnings (no lo he probado), desde el propio entorno virtual:

```
python -m pip install --upgrade pip
```

Tu prueba, si te marca bien la sintaxis entonces no hay problema.

**Comment by cjadeveloper** [comment]
Creo que el error me arrojó porque VSC intentó ejecutar pip como un módulo de python (con la opcion -m), no? Al hacer 

`python.exe -m pip install -U pylint`

Que diferencia hay de hacerlo así, a como lo hice yo manualmente? Con

`pip install -U pylint`

Lo que quiero entender, en realidad, es porque VSC busca hacer `python.exe -m pip install blablabla` y no directamente `pip install blablabla`. Aparte de porqué me arrojó esos errores. 

Quizás debiera empezar con una instalación limpia de VSC e intentarlo nuevamente. Pero tengo tantas extensiones en VSC instaladas y configuradas que me da pánico de solo pensarlo!!! :fearful:

**Comment by hcguz** [comment]
Entiendo. 

Si lo haces de la primera forma puedes instalar un paquete en un entorno sin necesidad de tenerlo activo, haciendo referencia a la ruta donde está el ejecutable de python y a su paquete pip. 

De la segunda forma necesitas estar dentro del entorno virtual y haces referencia directa a su paquete pip. 

La clave es que VSC maneja muchos entornos de ejecución, por lo que siempre ejecuta la primera forma para asegurarse de que es el entorno correcto el que instala el paquete de turno.
