### ISSUE TITLE
error CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>

### ISSUE THREAD

**Issue by epi-c** [hcosta/instalardjango.com#2]
hola, estoy siguiendo el curso de Udemy Curso Práctico de Django: Aprende Creando 3 Webs y al tirarme a la pagina https://hcosta.github.io/instalardjango.com/#win10 
seguí los pasos y todo bien, al consultar por la versión de python me arroja la 3.7.3

(base) C:\Windows\system32>python --version
Python 3.7.3

pero al intentar crear el ambiente me da el siguiente error:

(base) C:\Windows\system32>conda create -n py36 python=3.6
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

......................................................................................................................................
esto ocurre también si intento realizar un update de conda

(base) C:\Windows\system32>conda update conda
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

(base) C:\Windows\system32>

favor me puedes ayudar con este error.

saludos.

**Comment by hcguz** [comment]
Hola, la URL ahora prece cargar correctamente, ¿quizá era algo temporal y estaba el repositorio de Anaconda caido? Aún así creo que sería bueno probar con la versión 3.7:

```
conda create -n py37 python=3.7
```

**Comment by epi-c** [comment]
hola, vuelve a generar el mismo error, por lo que logro ver menciona un modulo SSL como no habilitado, ¿sabes como habilitar ese modulo desde conda? saludos.

![image](https://user-images.githubusercontent.com/17519389/63090075-1ac18d00-bf28-11e9-87b1-1e27c759b124.png)

**Comment by hcguz** [comment]
¿Has probado a ejecutarlo desde una terminal de Anaconda Prompt? Veo que estás en una CMD normal, quizá no encuentra algún módulo interno de anaconda.

**Comment by epi-c** [comment]
esta ejecución es desde Anaconda Prompt resultando el mismo error
![image](https://user-images.githubusercontent.com/17519389/63090364-0205a700-bf29-11e9-8c94-d64da660efbd.png)

adjunto algunos screen con info haber si sirven de apoyo

![image](https://user-images.githubusercontent.com/17519389/63090395-219ccf80-bf29-11e9-96fb-cdcb8dd66974.png)


quedo atento a su respuesta. saludos

**Comment by hcguz** [comment]
Según explican en esta página https://forum.qiime2.org/t/condahttperror-http-000-connection-failed/3317 parece que puede ser tu cortafuegos. Indican proceder ejecutando este comando antes de crear el entorno virtual, a ver si hay suerte:

```
conda config --set ssl_verify no
```

**Comment by epi-c** [comment]
sigue generando el mismo error, seguiré buscando haber si encuentro alguna solución y la comentaré aquí mismo, saludos

**Comment by epi-c** [comment]
Estimado, la solución la encontré en este link https://github.com/conda/conda/issues/8273 tuve que copiar dos archivos (libcrypto-1_1-x64.dll y libssl-1_1-x64.dll) desde C:\Miniconda3\Library\bin a C:\Miniconda3\DLLs, funco 100%

saludos y gracias por el apoyo

**Comment by hcguz** [comment]
> Estimado, la solución la encontré en este link [conda/conda#8273](https://github.com/conda/conda/issues/8273) tuve que copiar dos archivos (libcrypto-1_1-x64.dll y libssl-1_1-x64.dll) desde C:\Miniconda3\Library\bin a C:\Miniconda3\DLLs, funco 100%
> 
> saludos y gracias por el apoyo

Muchas gracias por aportar la solución, espero que no sea un problema generalizado.
