### ISSUE TITLE
Error al crear un entorno virtual

### ISSUE THREAD

**Issue by amparo-sonia12** [hcosta/instalardjango.com#4]
Hola buenas Noches.
Estoy siguiendo el curso de Udemy pero al momento de crear mi primer entorno virtual usando miniconda me arroja el error al ejecutar la sentencia:
`conda create -n py7 python-3.`7
 
El error que me arroja es el de:

Collecting package metadata (current_repodata.json): done
Solving environment: failed 

PackagesNotFoundError: The following packages are not available from current channels:
-python-3.7

Intente ejecutarlo desde la consola de anaconda pero de igual forma me dio error, también intente ejecutarlo como administrador y me arrojó el mismo resultado.

Podrías ayudarme con el error.

Un abrazo

**Comment by hcguz** [comment]
Hola fíjate como hay que indicar la versión:

`conda create -n py37 python==3.7 `

**Comment by amparo-sonia12** [comment]
Muchas gracias ya me permitió crear el entorno virtual, muchas gracias .

un abrazo
